name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.14.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: node.js ${{ matrix.node }} test in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn run build

  release:
    runs-on: ubuntu-latest
    name: 'Release to npm and gh-pages branch'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    strategy:
      matrix:
        node: ['12.14.1']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn run build
          yarn run generate:docs

      - name: Deploy document
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: ./docs
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
